openapi: 3.0.3
info:
  title: ACM UIUC Membership API
  version: "1.0.0"
  contact:
    name: ACM Infrastructure Team
    email: infra@acm.illinois.edu

servers:
  - url: membership.acm.illinois.edu


paths:
  /:
    get:
      summary: Get UI
      operationId: getui

      responses:
        200:
          description: OK


      x-amazon-apigateway-auth:
        type: NONE

      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:298118738376:function:infra-membership-api-lambda/invocations

  /api/v1/healthz:
    get:
      summary: Ping the API
      operationId: ping

      responses:
        200:
          description: OK


      x-amazon-apigateway-auth:
        type: NONE

      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:298118738376:function:infra-membership-api-lambda/invocations

  /api/v1/checkMembership:
    get:
      summary: Get ACM membership status for a given Illinois NetID.
      operationId: checkMembership
      parameters:
        - in: query
          name: netId
          schema:
            type: string
          required: true
          description: Illinois NetID to check.
      responses:
        200:
          description: OK

      x-amazon-apigateway-auth:
        type: NONE

      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:298118738376:function:infra-membership-api-lambda/invocations

  